# Konfiguracja Multitool
# Poziomy i ich ulepszenia

levels:
  1:
    efficiency: 1
    fortune: 1
    enchantments:
      - "efficiency:1"
      - "fortune:1"
      - "unbreaking:1"
    bonuses: []
    required_blocks: 10000
  2:
    efficiency: 2
    fortune: 2
    enchantments:
      - "efficiency:2"
      - "fortune:2"
      - "unbreaking:2"
    bonuses: []
    required_blocks: 30000
  3:
    efficiency: 3
    fortune: 3
    enchantments:
      - "efficiency:3"
      - "fortune:3"
      - "unbreaking:3"
    bonuses:
      - "0.1% szansy na otrzymanie bloku żelaza"
    required_blocks: 50000
  4:
    efficiency: 4
    fortune: 4
    enchantments:
      - "efficiency:4"
      - "fortune:4"
      - "unbreaking:4"
    bonuses:
      - "0.1% szansy na otrzymanie bloku żelaza"
      - "0.1% szansy na otrzymanie bloku złota"
    required_blocks: 100000
  5:
    efficiency: 5
    fortune: 5
    enchantments:
      - "efficiency:5"
      - "fortune:5"
      - "unbreaking:5"
    bonuses:
      - "0.1% szansy na otrzymanie bloku żelaza"
      - "0.1% szansy na otrzymanie bloku złota"
      - "Auto-wytapianie rud żelaza i złota"
    required_blocks: 200000
  6:
    efficiency: 6
    fortune: 6
    enchantments:
      - "efficiency:6"
      - "fortune:6"
      - "unbreaking:6"
    bonuses:
      - "0.1% szansy na otrzymanie bloku żelaza"
      - "0.1% szansy na otrzymanie bloku złota"
      - "Auto-wytapianie rud żelaza i złota"
      - "0.1% szansy na otrzymanie bloku diamentu"
    required_blocks: 500000
  7:
    efficiency: 7
    fortune: 7
    enchantments:
      - "efficiency:7"
      - "fortune:7"
      - "unbreaking:7"
    bonuses:
      - "0.1% szansy na otrzymanie bloku żelaza"
      - "0.1% szansy na otrzymanie bloku złota"
      - "Auto-wytapianie rud żelaza i złota"
      - "0.1% szansy na otrzymanie bloku diamentu"
      - "0.1% szansy na otrzymanie bloku emeraldu"
    required_blocks: 1000000

# Ustawienia prestiżu
prestige:
  enabled: true
  max_level: 10
  bonus_multiplier: 1.5
  enchantment_multiplier: 1.2
  required_blocks: 2000000

# Ustawienia wydajności
settings:
  auto_smelt:
    iron_ore: true
    gold_ore: true
  drop_chances:
    iron_block: 0.001
    gold_block: 0.001
    diamond_block: 0.001
    emerald_block: 0.001 