name: Multitool
version: 1.0
main: org.VodkaJpg.multitool.Multitool
api-version: 1.13
authors: [VodkaJpg]
description: Plugin dodający zaawansowany Multitool z systemem poziomów
commands:
  multitool:
    description: Główna komenda pluginu Multitool
    usage: /<command> [give|prestige|reload]
    aliases: [mt]
    permission: multitool.use

permissions:
  multitool.use:
    description: Pozwala na używanie podstawowych komend Multitool
    default: true
  multitool.admin:
    description: Pozwala na używanie komend administracyjnych Multitool
    default: op
  multitool.prestige:
    description: Pozwala na używanie komendy prestiżu Multitool
    default: op
