name: Multitool
version: 1.0
main: org.VodkaJpg.multitool.Multitool
api-version: 1.13
authors: [VodkaJpg]
description: Plugin dodający zaawansowany Multitool z systemem poziomów
commands:
  multitool:
    description: Główna komenda pluginu Multitool
    usage: /<command> [give|prestige|reload]
    aliases: [mt]
    permission: multitool.use

permissions:
  multitool.use:
    description: Pozwala na używanie podstawowych komend Multitool
    default: true
  multitool.admin:
    description: Pozwala na używanie komend administracyjnych Multitool
    default: op
  multitool.prestige:
    description: Pozwala na używanie komendy prestiżu Multitool
    default: op

enchants:
  lifesteal:
    name: Lifesteal
    description: Leczy gracza podczas atakowania przeciwników
    max-level: 3
    rarity: UNCOMMON
    target: WEAPON
    tradeable: true
    discoverable: true
  telekinetic:
    name: Telekinetic
    description: Automatycznie zbiera przedmioty do ekwipunku
    max-level: 1
    rarity: RARE
    target: TOOL
    tradeable: true
    discoverable: true
